version: "3.9"
services:
  media-display:
    build:
      context: .
      args:
        - STAGE=$STAGE
    environment:
      - STAGE
      - DISPLAY
      - SPOTIFYD_ARGS
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/build
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority:ro
    ports:
      - 443:443
      - 1313:1313
    restart: unless-stopped
